aerogear/aerogear-js-sdk

example/react-native/README.md, example/react-native/package.json, example/react-native/src/components/StartScreen.js, example/react-native/src/mobile-services.json
* Updated instructions to install the `react-native-cli`
* Core SDK gets installed with `npm install` from the packages folder
* Sample mobile-services.json file added (contents of keycloak config is
shown in example app)
=> ✨ Add the Core SDK to the react-native example

example/cordova/README.md, example/cordova/package.json, example/cordova/www/index.html, example/cordova/www/js/index.js, example/cordova/www/mobile-services.json
Makes the Cordova example work with Browserify using the UMD module. Broswerify can be installed locally but in this example i'm adding it to the dependencies and provide a npm script to generate the bundle.
=> browserify example

example/cordova/.gitignore, package.json, packages/core/package.json, packages/core/tsconfig.json, tsconfig.json
Fix Unit tests by adding ts-node as dev dependency.
ts-node is required to compile typescript unit tests.
=> Fix Unit tests by adding ts-node

packages/core-cordova/src/android/MobileCoreModule.java
`sdkVersion` metrics must be added by the JavaScript interface, however for explicitness it should be added in the Android module. This way if for some reason the value is not added by JS code, the element will still be there in the metrics payload.
The way this metrics is set is something like:
```javascript
function sendAppAndDeviceMetrics() {
this.getAppAndDeviceMetricsFromNativeModule()
.then(metrics => {
metrics.app.sdkVersion = this.getPluginVersionFromWherever();
// publish
});
}
=> Adds missing metric in Android module

packages/core/src/metrics/MetricsService.ts, packages/core/src/metrics/model/MetricsPayload.ts, packages/core/src/metrics/model/MetricsType.ts, packages/core/src/metrics/model/index.ts, packages/core/src/metrics/publisher/index.ts, packages/core/test/metrics/MetricsService.ts, packages/core/test/metrics/publiser/NetworkMetricsPublisher.ts
Adds the field `type` to the metrics payload. It is defined as a type with values `"init"` or `"security"` and it's extendable. This definition allows intellisense in Typescript.
=> Add metrics type

packages/core/src/configuration/ConfigurationParser.ts, packages/core/test/configuration/ConfigurationParser.ts, packages/core/test/mobile-config.json
Revert to the helper methods `getMetricsConfig()`, etc. 
`ServiceType` is now an enum that define the service type names as constants.
=> Revert config helper methods

packages/auth/package.json, packages/core/package.json
Make it easier for developers browsing npm to find the source repository here on GitHub.
Simple enough change that adds "repository" and "bugs" keys to the package.json of each module.
=> fix: add repository and issue tracker links to packages

packages/auth/package.json, packages/auth/src/AuthService.ts, packages/core/package.json, packages/core/src/index.ts, packages/core/src/metrics/MetricsService.ts
Add option to kill logging or extend it. We could add more debug stuff after and disable it for end users.
=> fix: add configurable logger to SDK

docs/core.adoc, packages/auth/src/AuthService.ts, packages/core/src/configuration/ConfigurationHelper.ts, packages/core/src/metrics/MetricsService.ts, packages/core/test/configuration/ConfigurationParser.ts, packages/core/test/metrics/MetricsService.ts
Use type for fetching mobile configurations instead of name.
Name is just human readable name and it's not guaranteed to be unique.
See: https://github.com/aerogear/aerogear-android-sdk/pull/217
=> fix: use type for config

packages/auth/src/AuthService.ts
Expose the config directly from auth instead of requiring the user to use the core.
=> added config method to auth

packages/security/src/SecurityService.ts, packages/security/src/deviceTrust/SecurityCheck.ts, packages/security/src/deviceTrust/SecurityCheckResult.ts, packages/security/src/deviceTrust/SecurityCheckType.ts, packages/security/src/deviceTrust/checks/NonRootedCheck.ts, packages/security/src/deviceTrust/checks/RootedCheck.ts, packages/security/src/deviceTrust/checks/index.ts, packages/security/src/deviceTrust/index.ts
Currently there is no API documentation for the security service.
Add API documentation for the security service.
There is also a small refactor of the `SecurityCheckType` module.
=> Add documentation and refactor check type

packages/security/src/SecurityService.ts, packages/security/test/SecurityService.ts
Currently the SecurityService can only perform single checks.
Allow for multiple checks to be passed to a `checkMany` function.
=> AEROGEAR-2687 Allow for multiple checks to be performed

packages/security-cordova/plugin.xml, packages/security/src/deviceTrust/SecurityCheckType.ts, packages/security/src/deviceTrust/checks/DebuggerCheck.ts, packages/security/src/deviceTrust/checks/NonDebugCheck.ts, packages/security/src/deviceTrust/checks/index.ts
https://issues.jboss.org/browse/AEROGEAR-2676
Currently, we do not have a check to see if a device is running in debug mode. This PR adds a debug check by using a cordova plugin which is added to our aerogear security plugin
The following PR can be used to verify these changes: https://github.com/aerogear/cordova-showcase-template/pull/29
In SDK root folder run:
```
npm install
npm run bootstrap
npm run build
```
cd to `cordova-showcase` and checkout above PR and run the following:
```
cordova plugin add --link <<path to security-cordova>>
npm install
npm run ionic:<<ios or android>>
```
=> AEROGEAR-2672 Implement debug security check

docs/security/security.adoc, packages/security-cordova/plugin.xml, packages/security/src/deviceTrust/SecurityCheckType.ts, packages/security/src/deviceTrust/checks/DeviceLockCheck.ts, packages/security/src/deviceTrust/checks/NonDebugCheck.ts, packages/security/src/deviceTrust/checks/NonEmulatedCheck.ts, packages/security/src/deviceTrust/checks/NonRootedCheck.ts, packages/security/src/deviceTrust/checks/index.ts
JIRA: https://issues.jboss.org/browse/AEROGEAR-2677
This is intended to replace #87
Added security check to check if the device lock is set or not.
Simplify the check performed in #87 based on the description and reading the code or https://github.com/shangyilim/cordova-plugin-pincheck. This also resolves an issue with iOS failure on a device.
* Run https://github.com/aerogear/cordova-showcase-template/tree/AEROGEAR-2526-security-checks (device or emulator).
* Ensure the check passes when a lock is set
* Ensure the check fails when a lock isn't set
* Run https://github.com/aerogear/cordova-showcase-template/tree/AEROGEAR-2526-security-checks (device only)
* Ensure the check passes when a lock is set
* Ensure the check fails when a lock isn't set
=> AEROGEAR-2677 Device lock security check

CONTRIBUTING.md, docs/contrib/contributing-guide.adoc, package.json
New version of lerna no longer using npm link. 
This means that to use modules outside (in showcase app ) we need to link them manually. @TommyJ1994 Hit issue when link was pointing to different source code. This PR resolves that.
Pinging various people just for information about new workflow in repo.
@aidenkeating @ciaranRoche @StephenCoady @TommyJ1994 @wei-lee 
```
npm run link
```
=> fix: add script and docs for link

docs/modules/getting-started/pages/security.adoc
Try to keep docs consistent across the SDKS
Small update to mention the custom self defence checks in the **package offers** section of the security doc.
This was added in the iOS SDK [here](https://github.com/aerogear/aerogear-ios-sdk/pull/111/commits/a018e256ed6eb734ce781cf43f577fecf728e5cc)
=> mention custom security checks in package offers section

scripts/validateRelease.sh
The previous regex was pretty flawed. It was only checking for the occurrence of one digit. e..g `1.2.3` is valid but `10.2.3` is not valid.
=> ci: fix git tag validation regex

packages/core/src/metrics/MetricsService.ts, scripts/cloneExamples.sh
* Metrics SDK was calling `Promise.resolve()` in error situations.
* `cloneExamples.sh` had a typo with some path names.
=> Minor fixes

packages/security/package.json
The peerDependency is outdated so that the installation throws a warning. Plus also a standard dependency is redundantly included.
The peerDependency is no needed because app package includes core, and app is always required. Packages are not installed twice.
=> Remove peer dependency in security

packages/security/src/deviceTrust/checks/NonRootedCheck.ts
Issue https://github.com/aerogear/aerogear-js-sdk/issues/105
Currently, RootBeer sometimes gives a false positive result to the check. This is often because the manufacturer of the device rom has left the busy box binary.
We have added a check to the Rootcheck to detect the device platform, as this is a specific problem for android. If the device is an android device we invoke the `isRootedRedBeer` function, this reduces the likely hood of a false positive result. If the device is not an android device we invoke the `isRooted` function.
**Important** I have verified this on an Android emulator only, this will need to be verified on an actual rooted device as well as ios to ensure it works.
Navigate to the device trust page in the showcase app and observe the result, if the device is …
=> Fix rooted check false positive

packages/auth/src/Auth.ts
Currently while running the showcase app keycloak fails to configure properly, this leaves any attempt to interact with keycloak as returning undefined.
This change just sets the internalConfig to the config file only, as clientId and the url is exposed through the config.
To verify boot up the showcase template application and run through the authentication process, the access control, and the network tab.
=> Fix - auth constructor config

.circleci/config.yml
CircleCI does a bad job of validating these tags. It is also redundant here because we do our own validation as part of the release. Much better for the release to kick off and fail over the release not ever kicking off because that would leave people very confused
=> ci: allow any tag to kick off release process

packages/security/src/deviceTrust/checks/NonRootedCheck.ts
Currently we are not invoking the Android check function in the
rooted check. The object we're checking will always evaluate to
true, meaning we're always trying to perform an Android-specific
check. Causing the check to crash on iOS.
This fixes the check by invoking the function.
=> Fix is rooted check by invoking android check function

packages/core/src/Core.ts
Currently, if there is a blank service object in the `mobile-service.json` it causes the SDK to fall over,  by handling it and returning the object as false, the core remains stable and the missing config is picked up by our individual modules on init.
- Remove one of the service objects and replace with a blank object in the example app
- Run the app, and it should crash on startup
- Symlink this PR changes to the example app.
- Rerun the app, it will not crash on startup
=> Add check to getConfigByType function

README.md
https://issues.jboss.org/browse/AEROGEAR-3584
As part of the jira mentioned above changes were made to add direct links as a fix to dead links appearing in our documentation
=> AEROGEAR - 3584 - direct links added to readme

.gitignore, package.json, scripts/docs.sh
Currently, the docs script falls over due to the Cordova plugins not containing an `src` directory. 
This change clones the docs.aerogear.org repo into the docs directory,  it pipes a different config to the `lerna.json`, this specifies the modules we want to generate documentation for. It runs the typedoc script and places the output in the appropriate location within the docs.aerogear.org repo. Before completing it pipes back in the old config to the `lerna.json` file
- Checkout PR
- Run `npm run generate:docs`
- Navigate to docs -> docs,aerogear.org -> api -> cordova -> latest to view the new documentation
- Rerun `npm run generate:docs`
- The script should run with no issue.
=> Refactor docs script

scripts/updatePluginXmlVersion.sh
The script didn't work on mac because `sed -i` on mac requires an additional parameter, not needed on GNU `sed`
=> Fixed updatePluginXmlVersion.sh to make it works on MAC

packages/sync/package.json, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/DefaultConfig.ts, packages/sync/src/conflicts/conflictLink.ts, packages/sync/src/conflicts/strategies.ts, packages/sync/src/createClient.ts, packages/sync/src/index.ts, packages/sync/src/links/LinksBuilder.ts
NOTE: Stalling work on this PR to focus on tickets being brought into the spring.
https://issues.jboss.org/browse/AEROGEAR-8091
Added a base for conflict detection. Also exports two basic strategies for use by the client.
First clone this branch and from within `packages/sync` run `npm link .`
Then from within the offline strategies repo, on this branch: https://github.com/aerogear/offline-conflict-strategies/pull/34
1. Run the server:
```
cd server
docker-compose up -d
npm i
npm run start
```
2. Run the app:
```
cd web
npm i
npm link @aerogear/datasync-js
npm run start 
```
3. Trigger the conflict:
When the app is running open two separate browser windows (must not both be the same browser - or one should be incognito).
Create a user and have it displayed on both windows.
Edit the user …
=> added base for conflict link

packages/sync-cordova/README.md, packages/sync-cordova/package.json, packages/sync-cordova/plugin.xml
I have created wrapper to follow patterns used in other SDK's (and documentation patterns). 
Before release we can verify if we use more than one plugin and validate if wrapper is still needed.
Using latest release
=> Wrapper for Cordova Plugins used for Sync

packages/sync/src/conflicts/conflictLink.ts, packages/sync/src/conflicts/index.ts, packages/sync/src/createClient.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/OfflineQueueLink.ts, packages/sync/src/offline/squashOperations.ts, packages/sync/test/OfflineQueueLink.test.ts, packages/sync/test/SquashOperation.test.ts, packages/sync/test/operations.ts
Adding noSquash feature as per: https://issues.jboss.org/browse/AEROGEAR-8146
NOTE: The ticket specifies an isSquashable directive as opposed to noSquash which is what I have implemented. I feel this makes more sense as the majority of mutations will be squashable so it is opt out of squashing as opposed to opt in.
To try this out add @noSquash to your query and ensure `directive @noSquash on FIELD` is present in your typeDefs.
If you want, those changes are already on the branch [here](https://github.com/aerogear/offline-conflict-strategies/tree/directives-test)
=> Aerogear 8146

packages/sync/src/config/Constants.ts, packages/sync/src/links/DirectiveLink.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/LocalDirectiveFilterLink.ts, packages/sync/src/links/OfflineQueueLink.ts, packages/sync/src/links/compositeQueueLink.ts, packages/sync/src/offline/squashOperations.ts, packages/sync/test/LocalDirectiveFilterLink.test.ts, packages/sync/test/OfflineQueueLink.test.ts, packages/sync/test/indexTest.ts, packages/sync/test/operations.ts
To check this works 
* Run the example application using master of the SDK.
* Do not add any directives to the schema on the server.
* Annotate one of the queries with either @onlineOnly or @noSquash e.g.
`updateUser(dateOfBirth: $dateOfBirth, id: $id, name: $name, version: $version) @onlineOnly`
* In the application run the query you previously annotated.
* You should see an error in the console stating that @onlineOnly or @noSquash is an unknown directive.
* Check out this branch on the SDK
* Leave the example application as before with whichever annotation you chose.
* Run the same query as before
* The query should succeed this time, or at least the directive should not cause an error
=> added directive link to overall links

packages/sync/README.md, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/SyncConfig.ts
Remove option to customize id as we no longer use any id related stuff. 
This means that we can settle with default _id/id. If users will want to change that we could expose it again, but it's best to stick with default
=> Remove option to customize id

.github/CODEOWNERS, packages/sync/README.md, packages/sync/package.json, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/createClient.ts, packages/sync/src/links/LocalDirectiveFilterLink.ts, packages/sync/src/links/OfflineQueueLink.ts, packages/sync/src/offline/OfflineQueueListener.ts, packages/sync/src/offline/OfflineRestoreHandler.ts, packages/sync/src/offline/index.ts
Allow to detect operations on queue in order to provide feedback for users and their UI. 
This simple listener can be extended over the time. For the moment we have:
- Detection of the element added to queue
- Detection of elements flushed from queue
This code will still be vulnerable to issues with RestoreHandler. 
I'm going to deal with this in separate PR as it's not as trivial as actual listener.
If you guys have idea about other methods that can be exposed let me know.
Verification will be possible on separate PR for ionic sample app- link soon.
Since there is no implementation on our side we do not have unit tests for this particular feature.
1. Please run example app using
https://github.com/aerogear/apollo-voyager-ionic-example/pull/5
2. Go offline
3. Add new item
4. See queue …
=> Add offline queue listener

packages/sync/package.json
Just version bump. Still development release, but dropped alpha sticker so our getting started will work without specifying exact version.
=> Release 0.1.0

packages/core/src/index.ts, packages/core/src/metrics/MetricsBuilder.ts, packages/core/src/metrics/MetricsService.ts, packages/core/src/metrics/index.ts, packages/core/src/metrics/platform/CordovaAppMetrics.ts, packages/core/src/metrics/platform/CordovaDeviceMetrics.ts, packages/core/test/metrics/MetricsBuilderTest.ts, packages/core/test/metrics/MetricsServiceTest.ts, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/SyncConfig.ts, packages/sync/src/createClient.ts, packages/sync/src/links/AuditLoggingLink.ts, packages/sync/src/links/LinksBuilder.ts
With this PR, GraphQL requests now have the client info (client id, app info, device info) in the extensions part of a request. That's only done when auditLogging is enabled.
The code that's collecting the client info is made reusable.
*NOTE*: Device/app/client info can't be collected in the browser. You need to verify using Cordova.
Get https://github.com/aerogear/apollo-voyager-server/pull/28
Execute 
```
npm install
npm run bootstrap
npm run compile
node examples/auditLogging/server.js
```
This will start the audit logging example where some audit logs are written to stdout with every request.
Gotta build and link the JS SDK.
Get this PR (https://github.com/aerogear/aerogear-js-sdk/pull/195)
Execute
```
npm install
npm run bootstrap
npm run build
npm run link
npm run bootstrap 
```
Get …
=> AEROGEAR-8027 - send client info when audit logging enabled

docs/contrib/releng.adoc, lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/push-cordova/package.json, packages/push/package.json, packages/security-cordova/package.json, packages/security/package.json, packages/sync-cordova/package.json, packages/sync/package.json
Core package is used as singleton and when having more than single instance of core app config will stop working. While this is only temporary fix for the invalid architecture it will provide cleaner way to manage core<> app dependency.
How things will work now:
- App will be required to configure entire platform and setup metrics
- Each individual package will be relying on the core provided in app dependency.
Eventually we can map app package to core and let it be used inside every SDK - however this will affect documentation and end user API so not sure if we are ok with this move.
EDIT:
Actually core.init and app init are the same so we could do that if you guys think this is the way to go.
=> fix: Move core to be in peerDependencies

packages/sync/README.md, packages/sync/integration_test/test/offline.test.js, packages/sync/src/cache/createOptimisticResponse.ts, packages/sync/src/links/OfflineQueueLink.ts
https://issues.jboss.org/browse/AEROGEAR-8444
Extracted from https://github.com/aerogear/aerogear-js-sdk/pull/213.
Allow updates on items created while offline. When back online, operations in mutations queue are send one by one (waiting for previous one to finish). If there was optimistic id for the operation, and server returns real id, next operations with this optimistic id in queue are updated with this new id.
This will only work until client is re-initialized - `replayOfflineMutations` does not have this change. https://github.com/jhellar/aerogear-js-sdk/pull/1 enables this also for `replayOfflineMutations`.
1. `npm link` those changes to `apollo-voyager-ionic-example` app
2. go offline
3. create item then make some updates on it
4. go back online
5. when offline updates are …
=> Allow updates on items created while offline

packages/sync/src/links/OfflineQueueLink.ts
https://issues.jboss.org/browse/AEROGEAR-8453
If there is a lot of operations in offline queue, client is going back online, then for example if client will update item (created while offline) while queue is being processed, it can happen that this update operation will happen before the create operation, so it will fail.
To prevent this, operations should be enqueued when processing queue, even if queue is open.
=> Enqueue incoming mutations while processing offline queue

packages/sync/README.md, packages/sync/src/links/OfflineQueueLink.ts, packages/sync/src/offline/OfflineQueueListener.ts
https://issues.jboss.org/browse/AEROGEAR-8345
=> Added notifications for success/failure for offline operations

packages/sync/src/createClient.ts
Cache by default will start removing data after reaching 1MB. 
This change disables that by default. It also removes debug statements to make cache much smaller in size.
=> fix: Disable garbage collecting of old cache entries.

packages/sync/src/createClient.ts
Saw the following error when I try to run the ionic-showcase app against an openshift cluster:
```
Error: Missing server URL
at new ConfigError (ConfigError.js:22)
at SyncConfig.push../node_modules/@aerogear/voyager-client/dist/config/SyncConfig.js.SyncConfig.validate (SyncConfig.js:50)
at extractConfig (createClient.js:93)
at Object.<anonymous> (createClient.js:59)
at step (createClient.js:32)
at Object.next (createClient.js:13)
at createClient.js:7
at new ZoneAwarePromise (zone.js:910)
at push../node_modules/@aerogear/voyager-client/dist/createClient.js.__awaiter (createClient.js:3)
at push../node_modules/@aerogear/voyager-client/dist/createClient.js.exports.createClient (createClient.js:54)
```
This PR fix the issue. It always use the urls from mobile-services.json file first, then …
=> fix:initialise the config object correctly

packages/sync/README.md, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/conflicts/ConflictResolutionStrategy.ts, packages/sync/src/conflicts/conflictLink.ts
Issue: [AEROGEAR-8382](https://issues.jboss.org/browse/AEROGEAR-8382) - #198 
- Added a new `ConflictResolutionStrategies` interface that allows passing pairs of `operationName` and `resolver` function.
- Added ability to work with both the old way (one function for all the operations) and the new way (one function for each operation)
=> Added ability to pass a resolver object

packages/auth/src/Auth.ts
Default value makes no sense and prevents from initializing keycloak without login operation.
Our default should be just empty/undefined value
=> BREAKING: Remove check-sso option as default param

packages/sync/integration_test/test/offline.test.js, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/OfflineLink.ts, packages/sync/src/offline/OfflineQueue.ts, packages/sync/src/offline/squashOperations.ts, packages/sync/src/utils/helpers.ts
This small change fixes a bug whereby the local only directives were not being removed from the document before being sent to the server.
Using this pr as the voyager-client in the showcase app, add @onlineOnly directive or @noSquash directive to the mutations and verify that everything works as expected.
@wtrocki we should probably add some feedback to the app as part of onlineOnly throwing an error in the client (at the moment its just in the console). however it will be hard to differentiate from a normal network error and an intentional one from onlineOnly. any thoughts?
=> fix: changed link flow to fix local directives

packages/sync/package.json
Fix random crashes of the client when websockets are initiated too fast.
Errors that happening breaking entire client.
The solution is to use the latest version of the error package that has this fixed:
https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-error/src/index.ts#L67-L70
=> fix: Bump version of error link

packages/push/src/PushRegistration.ts
https://issues.jboss.org/browse/AEROGEAR-8589
It seems like the ups-config is using `variantId` while UPS itself uses `variantID`. So the push sdk should be able to handle both. It should also check both `variantId` and `variantSecret` are valid, otherwise it should return an error.
=> fix: use either variantId or variantID for push

docs/templates/package.json, package.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/push/package.json, packages/security/package.json, packages/sync/package.json, packages/sync/src/links/LocalDirectiveFilterLink.ts, tslint.json
The reason we were experiencing compiler issues is that the versions of `@types/node` and `typescript` we were using were incompatible. Basically, there were some things that were being defined by both TypeScript and by the `types/node` lib.
In my opinion the simplest fix here is to bring both of those to the latest version.
=> fix: update to latest typescript

packages/sync/README.md, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/SyncConfig.ts, packages/sync/src/conflicts/ConflictResolutionStrategy.ts, packages/sync/src/conflicts/conflictLink.ts, packages/sync/src/conflicts/strategies.ts, packages/sync/src/createClient.ts, packages/sync/test/SyncConfigTest.ts
small fix to add a default to the conflictResolutionStrategy Interface. This means that if the user provides a resolution function for a specific mutation then they do not need to name all as the default can also be defined.
=> fix: fix broken conflict resolver check

scripts/validateRelease.sh
Similar with https://github.com/aerogear/voyager-server/pull/126
@wtrocki In Voyager server if there's a compilation error, dist folder is empty. But not in JS sdk.
I couldn't figure out why.
Anyway, this is not the perfect check, but it would be thought as a smoke check only.
=> AEROGEAR-8560 check compile success during release validity

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json, packages/sync-cordova/package.json, packages/sync-cordova/plugin.xml, packages/sync/package.json
- FIX: Updated to latest versions of Apollo Client and related libraries
- BREAKING: New way to configure conflict resolution using an object format:
`conflictStrategy: clientWins` => `conflictStrategy:{ default:clien
=> chore: release 2.2.0

packages/sync/integration_test/test/offline.test.js, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/SyncConfig.ts, packages/sync/src/conflicts/ObjectState.ts, packages/sync/src/conflicts/VersionedState.ts, packages/sync/src/conflicts/index.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/OfflineLink.ts, packages/sync/src/offline/OfflineQueue.ts
this is a small change to implement sequential ordering of the offline queue. this is needed to stop client data conflicting with itself.
=> fix: implement sequential ordering of offline queue items

packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/SyncConfig.ts, packages/sync/src/links/AuthLink.ts, packages/sync/src/links/ExtensionsLink.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/OfflineLink.ts, packages/sync/src/links/RetryLink.ts, packages/sync/src/offline/OfflineQueue.ts, packages/sync/src/offline/OfflineQueueListener.ts, packages/sync/src/offline/OfflineRestoreHandler.ts, packages/sync/src/offline/OperationQueueEntry.ts, packages/sync/src/offline/retry/RetriableOperation.ts, packages/sync/src/offline/retry/ShouldRetry.ts, packages/sync/src/utils/helpers.ts
The queue should be processed when offline only.
Mutations should be marked as offline to enqueue them from offline mutation handler. Posting for early feedback. Please shout as soon as you see something wrong
I have performed testing for all possible cases but feel free to chime in with testing.
- Offline changes restored when server is down
- Offline changes ending up with graphql error
- Offline changes are successful.
=> Process queue only when offline

packages/security/package.json, packages/security/src/appSecurity/AppSecurity.ts, packages/security/test/config/mobile-services.json
https://issues.jboss.org/browse/AEROGEAR-8772
Create a class in the security-services that uses the aerogear-js-sdk init for enabling and disabling
Implementation is similar to the Auth package
https://github.com/aerogear/aerogear-js-sdk/blob/964a45b0a851720410b68958774ed0f97e7d6785/packages/auth/src/Auth.ts#L17
https://github.com/aerogear/aerogear-js-sdk/blob/964a45b0a851720410b68958774ed0f97e7d6785/packages/push/src/PushRegistration.ts#L23
https://github.com/aerogear/aerogear-js-sdk/blob/964a45b0a851720410b68958774ed0f97e7d6785/packages/sync/src/config/SyncConfig.ts#L26
No Verification steps as this is a constructor
=> AEROGEAR-8664

packages/security/package.json, packages/security/src/appSecurity/AppSecurity.ts, packages/security/src/index.ts
Merging to feature branch `app-security`
PR Post modified device data and app data to the security services app-service module
returns a promise from axios
Needed for the Mobile security service Go server app-security integration
https://issues.jboss.org/browse/AEROGEAR-8774
- node 10
- npm 6
- install ionic https://ionicframework.com/docs/installation/cli
- install android sdk 26 http://www.androiddocs.com/sdk/installing/adding-packages.html
- clone this repo
- checkout branch AEROGEAR-8774
- install the aerogear-js-sdk
```bash
npm i && npm run bootstrap && npm run build
```
- clone https://github.com/austincunningham/ionic-showcase.git
- checkout branch AEROGEAR-8773
- change the package.json to point at your local clone of aerogear-js-sdk e.g.
> Note you can try and use npm link but I …
=> AEROGEAR-8774 post client data to go mobile security service

packages/sync/package.json, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/SyncConfig.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/test/SyncConfigTest.ts
added the apollo retry link to retry mutations which have failed and were previously queued offline.
1. Go offline
1. Create a couple of mutations
1. Stop the server
1. Go back online
1. Mutations should be attempted to be replayed after 1 second and should be retried 5 times. If they are unsuccessful they should remain in the queue. If they are successful they should be removed from the offline queue.
=> feat: added retryLink for offline queued mutation failures

packages/core/src/metrics/DefaultMetricsBuilder.ts, packages/core/src/metrics/MetricsService.ts, packages/core/src/metrics/index.ts, packages/core/src/metrics/model/MetricsBuilder.ts, packages/core/src/metrics/model/index.ts, packages/core/test/metrics/MetricsBuilderTest.ts, packages/core/test/metrics/MetricsServiceTest.ts, packages/security/package.json, packages/security/src/appSecurity/AppSecurity.ts, packages/security/src/index.ts, packages/security/test/AppSecurityTest.ts, packages/sync/src/links/LinksBuilder.ts
Merging to feature branch `app-security`
PR uses the metrics services with new publisher to post metrics data
returns a promise
Needed for the Mobile security service Go server app-security integration
https://issues.jboss.org/browse/AEROGEAR-8911
- node 10
- npm 6
- install ionic https://ionicframework.com/docs/installation/cli
- install android sdk 26 http://www.androiddocs.com/sdk/installing/adding-packages.html
- cordova 8.1.2
- clone this repo
- checkout branch AEROGEAR-8911
- install the aerogear-js-sdk
```bash
npm i && npm run bootstrap && npm run build
```
- clone https://github.com/austincunningham/ionic-showcase.git
- checkout branch AEROGEAR-8773
- change the package.json to point at your local clone of aerogear-js-sdk e.g.
> Note you can try and use npm link but I didn't have …
=> Aerogear-8911 refactor to use metrics service

packages/sync/src/links/WebsocketLink.ts
Related PRs:
* https://github.com/aerogear/ionic-showcase/pull/175
* https://github.com/aerogear/voyager-server/pull/164
This PR makes a tiny change so the full `Authorization` header is sent in the `connectionParams` for the WebSocketLink. The reason to do it this way is because it's compatible with things like GraphQL playground / Altair as well. This means we can do subscriptions + keycloak properly from those environments also.
I had to research this a little bit because I wasn't sure how the data is being sent and parsed on the server side.
It turns out once the websocket connection is negotiated an initial message is sent from the client to the server to say hello. The payload of that message is usually empty but if a `connectionParams` is provided it will be sent and on the server …
=> fix: pass auth header in connection params in websocket link

packages/sync/src/cache/IDProcessor.ts, packages/sync/src/conflicts/ConflictProcesor.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/offline/OfflineLink.ts, packages/sync/src/offline/OfflineQueue.ts, packages/sync/src/offline/procesors/IResultProcessor.ts
Add the ability to inject different processors when processing offline results. 
Different processors can be injected to review the data. 
Currently, we have:
- id processor that will be injected from the cache layer and bound to helpers we provide. However, if someone is not using our helpers they may decide to not use those. 
- conflict processor (optional with no conflicts involved)
=> fix: Add results processor abstraction

packages/sync/package.json, packages/sync/src/cache/createMutationOptions.ts, packages/sync/src/cache/createSubscriptionOptions.ts, packages/sync/test/CacheHelpersTest.ts, packages/sync/test/mock/mutations.ts
This PR does two things.
1. Need to expose the getUpdateFunction so that a developer can manually generate cache update functions. Main usage is for storing cache update functions across device restarts.
see: https://github.com/aerogear/ionic-showcase/pull/183/files#diff-f8726a2856d5cf9931bf35cf2e8280a4R15 
2. It changes the interface so that `createMutationOptions` can now accept an array of type `Query` as well as a single Query.
The function signature is now one of the following:
```
createMutationOptions({
mutation: DocumentNode,
variables: OperationVariables,
updateQuery: { query: GET_TASKS, variables: {...} },
typeName: string,
operationType: CacheOperation,
idField: string
});
createMutationOptions({
mutation: DocumentNode,
variables: OperationVariables,
updateQuery: [ 
{ query: …
```
=> fix: expose update function

packages/push/src/PushRegistration.ts, packages/push/test/PushRegistrationTest.ts, packages/push/test/indexTest.ts
When app is running on Android devices, subscribe the it in the Firebase Cloud Messaging topics using the UnifiedPush Server VariandID, and the categories used in the registration process. That is how UnifiedPush Server send message to the Android devices using no criteria and a specifically category name.
PS: There is more work to be done like add a unregistered method but it will be done in another issues/PR
Related Issue:
* [AEROGEAR-9176](https://issues.jboss.org/browse/AEROGEAR-9176)
**Sending message for all devices**
**Sending message for an specifically alias**
**Sending message for an specifically category** 
This requires [this PR](https://github.com/aerogear/ionic-showcase/pull/182)
=> Subscribe alias topic

packages/push/test/PushRegistrationTest.ts
In CI environment this test sometimes fails because of the default timeout 2s -> increased timeout to 10s.
```
> @aerogear/push@2.5.1 test /home/jenkins/workspace/integration-tests/aerogear-js-sdk/packages/push
> mocha
Registration tests
#register
✓ should fail to register in push server
1) should register in push server
1 passing (2s)
1 failing
1) Registration tests
#register
should register in push server:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/jenkins/workspace/integration-tests/aerogear-js-sdk/packages/push/test/PushRegistrationTest.ts)
```
=> increased timeout for push-registration test

packages/security-cordova/plugin.xml
The `cordova-security` plugin should require `@aerogear/cordova-plugin-iroot:0.8.1` in order to fix compatibility issues with cordova 9 [1]
1. https://issues.jboss.org/browse/AEROGEAR-9087
=> AEROGEAR-9323: Migrate cordova security plugin to aerogear iroot fork

packages/push/src/PushRegistration.ts, packages/push/test/PushRegistrationTest.ts
```
git clone https://github.com/aerogear/aerogear-unifiedpush-server.git
cd aerogear-unifiedpush-server
mvn clean install -DskipTests && docker run -p 9999:8080 -it aerogear/unifiedpush-configurable-container:2.2.2-SNAPSHOT
```
1. Register the device on UPS
1. Check if the device is listed on the UPS UI
1. Put the app in background
1. Send a message to the device (don't add any criteria) 
* The device should receive a message show it on the 
1. Send a message to the device (using whatever category used) and check if the message was
* The device should receive a message show it on the notification bar
1. Unregister the device on UPS
1. Check if the device gone from the UPS UI
1. Put the app in background
1. Send a message to the device (don't add any criteria) 
* Make sure the device …
=> Unsubscribe Android device from Firebase topic when unregister from UPS

packages/push/src/PushRegistration.ts, packages/push/test/PushRegistrationTest.ts
This is the last part of move all [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) code from the [ionic-showcase](https://github.com/aerogear/ionic-showcase/blob/a2b3ed008c2de92fbc4caae89f9839f311d3e591/src/app/services/push.service.ts) to js-sdk. 
This PR change the way how to use the push on Cordva/Ionic
Right now is not required that developer need to deal with phonegap-push-plugin anymore. The js-sdk do all pre-req needed on phonegap-push-plugin behind of the scene.
Related issues: [AEROGEAR-9557](https://issues.jboss.org/browse/AEROGEAR-9557)
```javascript
import { PushRegistration } from "@aerogear/push";
const push = PushNotification.init({
android: {},
ios: {
alert: "true",
badge: "true",
sound: "true"
}
});
// Registration on phonegap-push-plugin …
```
=> Push message received

packages/sync/package.json, packages/sync/src/config/SyncConfig.ts, packages/sync/test/mock/TestUtils.ts
Motivation - Offline package was exporting to many packages. 
This caused conflicts between existing packages that should be required on top level. Cleaned things in offix and reverted packages back to package.json
=> fix: Add extra packages to package.json for sync

packages/push/src/PushRegistration.ts
This PR prevents the registration try when configuration not found
=> Fix a validation error when config not found on Push

.circleci/config.yml, package.json, scripts/publishRelease.sh, scripts/versionMaster.sh
Motivation: https://issues.jboss.org/browse/AEROGEAR-9334
=> Release master

packages/auth/src/Auth.ts, packages/sync/src/auth/AuthContextProvider.ts, packages/sync/src/links/WebsocketLink.ts
Removes the `clientId` property from the header that would be sent by the sync SDK as part of websocket connections. Relates to https://github.com/aerogear/keycloak-connect-graphql/pull/23
=> fix: remove clientId from sync header payloads

scripts/validateRelease.sh
publishing master fails: https://circleci.com/gh/aerogear/aerogear-js-sdk/2076?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
This fixes script that validates versions.
=> fix: version validation

packages/security/src/appSecurity/AppSecurity.ts
fix for https://issues.jboss.org/browse/AGMS-662
- clone this repo and checkout this branch AGMS-662
- install the sdk 
```bash
npm i -g lerna
npm run cleanInstall
npm run build
```
- clone the ionic-showcase https://github.com/aerogear/ionic-showcase
- change the mobile-services.json to 
```json
{
"version": 1,
"namespace": "voyager",
"clientId": "voyager-ionic-example",
"services": [
{
"id": "security",
"name": "security",
"type": "security",
"url": "https://route-mobile-security-service.apps.mdsdemo-710a.openshiftworkshop.com/"
}
]
}
```
Change the package.json in the showcase to point to your local copy of the security package in the aerogear-js-sdk e.g.
```json
"@aerogear/push": "2.6.0",
"@aerogear/security": "file:/path to your clone copy/aerogear-js-sdk/packages/security",
```
- …
=> fix(undefined url): Application Trust is breaking showcase(AGMS-662)

packages/core/src/config/AeroGearConfiguration.ts
The configuration file generated by MDC may not have `version` and `clusterName` fields. Make them optional.
=> Make the version and clusterName fields optional

packages/push-cordova/plugin.xml
This PR update the phonegap-plugin-push dependency to solve the token problem on iOS 13.
For more details see: [AEROGEAR-9939](https://issues.jboss.org/browse/AEROGEAR-9939)
=> Update phonegap-plugin-push to support iOS 13
