aerogear/aerogear-js-sdk

docs/contributing-guide.adoc, docs/metrics/README.adoc
Contributing guide (developer getting started guide). 
Guide will evolve over the time. I wanted to provide just minimal set of instructions and general idea how SDK will be used.
=> Temporary contributing guide

.gitignore, packages/core/package.json, packages/core/tsconfig.json, tsconfig.json
@wtrocki This should allow for running unit tests
=> Fix running of unit tests

example/react-native/src/components/StartScreen.js, packages/core/package.json
fixes a issue with the webpack bundling for react native and a small style warning.
=> fix react-native bundle issue

packages/core/tsconfig.json
Fix for issue in: https://github.com/aerogear/aerogear-js-sdk/pull/23
=> Remove test from tsconfig

example/cordova/config.xml, example/cordova/package.json, example/cordova/www/index.html, example/cordova/www/js/index.js, example/cordova/www/pages/metrics.html, example/cordova/www/pages/template.html, package.json, packages/core-cordova/README.md, packages/core-cordova/package.json, packages/core-cordova/plugin.xml, packages/core-cordova/src/android/MobileCoreModule.java, packages/core-cordova/www/core-cordova.js
https://issues.jboss.org/browse/AGCORDOVA-199
TODO
Do not merge, work in progress.
=> [WIP] Implementation of native code wrapper for Cordova

packages/core/src/configuration/AerogearConfiguration.ts, packages/core/src/configuration/ConfigurationParser.ts, packages/core/src/configuration/index.ts, packages/core/src/index.ts, packages/core/src/metrics/MetricsService.ts, packages/core/src/metrics/model/AppMetrics.ts, packages/core/src/metrics/model/DeviceMetrics.ts, packages/core/src/metrics/model/index.ts, packages/core/src/metrics/publisher/MetricsPublisher.ts, packages/core/src/metrics/publisher/NetworkMetricsPublisher.ts, packages/core/src/metrics/publisher/index.ts
Make all exports non-default.
Create index files in src folders to import classes and interfaces in a cleaner way.
=> Refactor imports

packages/core/src/configuration/index.ts, packages/core/src/metrics/MetricsService.ts, packages/core/src/metrics/publisher/NetworkMetricsPublisher.ts, packages/core/src/metrics/publisher/index.ts
=> Fix some names

README.md
=> Add lerna badge in Readme

packages/auth/package.json, packages/auth/src/AuthService.ts
Remove BlueBird and use Native promise as part of the project
=> fix: Move to native promise

lerna.json, packages/auth/package.json, packages/metrics-cordova/package.json
Note: core was already at 0.2.0 so that this change doesn't appear in the diff.
=> Release version 0.2.0

packages/security-cordova/README.md, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/.npmignore, packages/security/package.json, packages/security/src/SecurityService.ts, packages/security/src/deviceTrust/SecurityCheck.ts, packages/security/src/deviceTrust/SecurityCheckResult.ts, packages/security/src/deviceTrust/SecurityCheckType.ts, packages/security/src/deviceTrust/checks/RootedCheck.ts, packages/security/src/deviceTrust/checks/index.ts, packages/security/src/deviceTrust/index.ts, packages/security/src/index.ts, packages/security/test/MockCheck.ts, packages/security/test/SecurityService.ts, packages/security/test/mocha.opts, packages/security/tsconfig.json
https://issues.jboss.org/browse/AEROGEAR-2674
Add a way to run/create own tests based on the Android SDK.
=> AEROGEAR-2527 Initial approach for device checks SDK

packages/security-cordova/plugin.xml, packages/security/src/deviceTrust/SecurityCheckType.ts, packages/security/src/deviceTrust/checks/NonEmulatedCheck.ts, packages/security/src/deviceTrust/checks/index.ts
JIRA: https://issues.jboss.org/browse/AEROGEAR-2680
Added the emulator security check
=> AEROGEAR-2680 - add emulator security check

.gitignore, docs/antora.yml, docs/local-site.yml, docs/modules/ROOT/_attributes.adoc, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/_attributes.adoc, docs/modules/ROOT/pages/index.adoc, package.json
adding antora structure to docs, 
need to follow up with another PR where I move files around, but want to merge this one just to validate publishing
=> mobdoc19 add antora structure

docs/security/security.adoc
JIRA - https://issues.jboss.org/browse/AEROGEAR-2678
Adds documentation to outline what the checks are, what type of checks we offer, and how to invoke these checks
=> AEROGEAR-2678 - Add Security Docs

lerna.json, package.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/security-cordova/package.json, packages/security/package.json, packages/security/src/SecurityService.ts
=> Release 0.3.0

docs/modules/getting-started/pages/security.adoc
This is currently documented in the Android SDK, but not in the JS SDK.
Document the basics on how to create a custom check. Similar to the Android documentation.
=> Add documentation on implementing a custom check

packages/auth/src/Auth.ts
Add ClientId Handler / Use Top Level Keycloak URL
=> Add ClientId Handler / Use Top Level Keycloak URL

docs/contrib/contributing-guide.adoc
Added some notes to get the user started developing on the sdk. As per AEROGEAR-2789
=> Updated the contributing readme

docs/modules/getting-started/pages/security.adoc, packages/core/src/metrics/platform/CordovaAppMetrics.ts, packages/core/src/metrics/platform/CordovaDeviceMetrics.ts
See issue #106 
See issue #106
=> Improve error output and doc for security metric publishing

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/plugin.xml, packages/security/package.json
=> Release 0.4.0

.circleci/config.yml
Update circle Ci commands for release
See: https://circleci.com/gh/aerogear/aerogear-js-sdk/451
=> fix: Update circle Ci commands for release

packages/push/package.json
=> fix: add access publicz

README.md, docs/modules/ROOT/pages/push.adoc
Improving documentation based on product owner input
=> Documentation improvements based on feedback

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json, scripts/prepareRelease.sh
=> release version 1.0.0-alpha

packages/security-cordova/plugin.xml
https://github.com/shangyilim/cordova-plugin-pincheck/pull/4
This change bumps the version on the pin check plugin
=> Bump pin check plugin version

packages/push-cordova/plugin.xml
Made changes to push plugin in order to get things installed.
=> Add required variables to phonegap plugin

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json
We need to push a release to test some small changes and fixes ahead of the community release
=> Release version 1.0.0-alpha.1

docs/contrib/releng.adoc
Small typo in the release docs, update script name
=> Fix typo in docs

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json
=> release version 1.0.0

packages/push/src/PushRegistration.ts
Rename plugin. See https://github.com/aerogear/aerogear-js-sdk/issues/140
=> Rename log message to push plugin

scripts/prepareRelease.sh
This will update all the packages - not only changed ones
=> Force all packages to be changed by publish

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json
Release 2.0.0
Breaking changes for security
=> Release 2.0.0

packages/core/src/Core.ts, packages/sync/integration/index.ts, packages/sync/package.json, packages/sync/src/config/ConfigError.ts, packages/sync/src/config/DataSyncClientConfig.ts, packages/sync/src/config/DefaultConfig.ts, packages/sync/src/createClient.ts, packages/sync/src/index.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/WebsocketLink.ts
Provide more advanced architecture that will be easier to test
Add example for links - now developers will be able to drop in links into default chain.
=> Sync ws support

packages/sync/src/conflicts/conflictLink.ts
Check if conflict link data is present before processing conflict
=> Check if conflict link data is present before processing conflict

packages/sync/src/config/SyncConfig.ts, packages/sync/src/createClient.ts, packages/sync/test/SyncConfigTest.ts
There is not much we can tests down here due to fact that we mostly wrapping things.
Created tests for config. 
More suitable tests will be applied to actual links.
=> Add config unit tests

packages/sync/src/createClient.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/offline/CordovaNetworkStatus.ts, packages/sync/src/offline/SyncOfflineMutation.ts, packages/sync/src/offline/WebNetworkStatus.ts
Minor fixes in order to compile code
=> Minor fixes to network status

packages/sync/src/createClient.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/QueueLink.ts, packages/sync/src/offline/OfflineRestoreHandler.ts, packages/sync/src/utils/helpers.ts, packages/sync/test/QueueLink.test.ts
Move network and storage inside link to make it self contain.
@StephenCoady we need see how we can get offlineQueue restored.
=> Refactor for offline queue

packages/sync/src/links/QueueLink.ts, packages/sync/src/offline/squashOperations.ts
=> removed squash to separate function

packages/sync/README.md, packages/sync/package.json, packages/sync/src/config/Constants.ts, packages/sync/src/links/OfflineQueueLink.ts, packages/sync/src/offline/OfflineRestoreHandler.ts, packages/sync/src/offline/squashOperations.ts
=> Add debug logging

packages/sync/test/OfflineQueueLink.test.ts, packages/sync/test/SquashOperation.test.ts, packages/sync/test/operations.ts
added some tests for the already existing @onlineOnly directive.
=> add onlineOnly tests

packages/sync/package.json, packages/sync/src/createClient.ts
Add missing return type for client.
Map existing complex type into simple one to simplify import on client side.
=> Expose client type

packages/sync/package.json
=> Release bump

packages/sync/src/cache/createOptimisticResponse.ts, packages/sync/test/createOptimisticResponseTest.ts
Add option to disable generating ID for responses.
=> fix: Add flag to not generate id for responses

packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/LocalDirectiveFilterLink.ts, packages/sync/src/links/OfflineQueueLink.ts, packages/sync/src/links/compositeQueueLink.ts, packages/sync/test/createOptimisticResponseTest.ts
Just some style/code improvements
=> Code improvements

packages/sync/README.md
I run thru docs again and found some missing pieces. Added this info now so we can consider it being complete.
=> Add info about mapping server and client ID's

packages/sync/README.md, packages/sync/src/config/SyncConfig.ts
- Add missing info about queries to docs
- Fix broken defaults for squashing
=> Docs improvements

packages/sync/src/config/SyncConfig.ts, packages/sync/src/createClient.ts
Make platform config less important than app config
Add support for websockets.
@secondsun do we have config for websocket ?
=> Openshift integration

packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/push/package.json, packages/security/package.json, packages/sync/package.json, packages/sync/src/config/SyncConfig.ts
Bump version of the core in order to release it.
TL;DR - I do not want to release entire set of the packages.. just do minor bump of the core and try it first
It may happen that this stuff is broken anyway so do not want to affect other SDK's
will test it on sync that is not used by anyone
=> fix: bump version of the core

packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/DefaultHeaderProvider.ts, packages/sync/src/config/HeaderProvider.ts, packages/sync/src/config/SyncConfig.ts, packages/sync/src/links/HeadersLink.ts, packages/sync/src/links/LinksBuilder.ts
https://issues.jboss.org/browse/AEROGEAR-8294
=> Data sync protected

packages/sync/package.json, packages/sync/src/conflicts/conflictLink.ts
Adjust client to api changes on server
=> adjust api changes on server 

packages/sync/package.json, packages/sync/src/config/SyncConfig.ts, packages/sync/src/conflicts/conflictLink.ts, packages/sync/test/SyncConfigTest.ts
Conflict error happens even when is resolved on client.
We should clean error as original error was handled.
=> fix: Eat error for client

packages/sync/package.json, packages/sync/src/config/SyncConfig.ts, packages/sync/src/conflicts/conflictLink.ts, packages/sync/test/SyncConfigTest.ts
=> Conflict improved

scripts/publishRelease.sh
Add references to relevant tickets or a short description about what motivated you do it. (E.g JIRA: https://issues.jboss.org/browse/AEROGEAR-{} AND/OR ISSUE: https://github.com/aerogear/standards/issues/{}) 
Add an short answer for: What was done in this PR? (E.g Don't allow users has access to the feature X.)
Add an short answer for: Why it was done? (E.g The feature X was deprecated.)
Add an short answer for: How it was done? (E.g By removing this feature from ... OR By removing just the button but not its implementation ... ) 
Add the steps required to check this change. Following an example.
1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item 
4. Check if in the left menu the feature X is not so long present.
PS.: Add images and/or .gifs to …
=> fix: correct argument for lerna publish

.circleci/config.yml, packages/sync/integration_test/karma.conf.js, packages/sync/integration_test/package.json, packages/sync/integration_test/server/graphql.js, packages/sync/integration_test/server/index.js, packages/sync/integration_test/server/schema.js, packages/sync/integration_test/server/subscriptions.js, packages/sync/integration_test/test/offline.test.js, packages/sync/integration_test/utils/graphql.queries.js, packages/sync/integration_test/utils/mocha.js, packages/sync/integration_test/utils/network.js, packages/sync/integration_test/utils/server.js, packages/sync/integration_test/utils/testApolloLink.js, packages/sync/integration_test/utils/waitFor.js, packages/sync/package.json, packages/sync/test/operations.ts
https://issues.jboss.org/browse/AEROGEAR-8111
- added integration tests for offline mutations
Tests implemented with Karma.
=> Added integration tests for DataSync

packages/auth/package.json
This is really important version bump as it will allow us to adapt new type of flow called `cordova-native`:
https://github.com/keycloak/keycloak/pull/5387/files
This flow enables much easier integration using tabbed interface. We will need to test it within our integrations and release new version to users. 
Huge thanks to @slaskawi for ideas.
=> Update keycloak library in Auth SDK

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json, packages/sync-cordova/package.json, packages/sync-cordova/plugin.xml, packages/sync/package.json
Bump version 2.1.0-rc1 to test new keycloak cordova-native functionality
=> feat: bump version 2.1.0-rc1

packages/sync/README.md, packages/sync/package.json
As we still making changes inside Auth we going to publish all packages soon.
=> BREAKING: Rename package to conform with the upstream name

packages/sync/README.md, packages/sync/src/config/DataSyncConfig.ts
=> Client docs for conflicts

packages/sync/integration_test/server/graphql.js, packages/sync/integration_test/server/index.js, packages/sync/integration_test/server/schema.js, packages/sync/integration_test/test/offline.test.js, packages/sync/integration_test/utils/graphql.queries.js, packages/sync/integration_test/utils/server.js, packages/sync/integration_test/utils/testStore.js
https://issues.jboss.org/browse/AEROGEAR-8111
Refactored integration tests so that test cases don't depend on each other.
=> Refactored integration tests for sync

packages/sync/integration_test/package.json, packages/sync/integration_test/server/graphql.js
=> Update integration tests

packages/sync/package.json, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/links/FileLink.ts, packages/sync/src/links/LinksBuilder.ts
Enable file uploads by adding file upload link
=> feat: Enable file uploads

packages/auth/src/Auth.ts, packages/auth/tsconfig.json, packages/sync/src/config/AuthContextProvider.ts, packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/HeaderProvider.ts, packages/sync/src/config/index.ts, packages/sync/src/createClient.ts, packages/sync/src/links/HeadersLink.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/WebsocketLink.ts
Related to: 
https://github.com/aerogear/ionic-showcase/pull/50 <--- verification steps
https://github.com/aerogear/voyager-server/pull/105
=> e2e subscriptions

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/push-cordova/package.json, packages/push/package.json, packages/security-cordova/package.json, packages/security/package.json, packages/sync-cordova/package.json, packages/sync/package.json
=> fix: Release 2.1.0

.circleci/config.yml, scripts/prepareRelease.sh
=> fix: release script fixes and use Node.js LTS in CI

package.json
=> fix: minor dev dependency updates

package.json, packages/push/test/PushRegistrationTest.ts, packages/security/test/SecurityService.ts, packages/security/test/mocks/MockCheck.ts
=> fix: update top level dependencies

packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/config/SyncConfig.ts, packages/sync/src/conflicts/ConflictListener.ts, packages/sync/src/conflicts/ConflictResolutionStrategy.ts, packages/sync/src/links/AuditLoggingLink.ts, packages/sync/src/links/LinksBuilder.ts, packages/sync/src/links/LocalDirectiveFilterLink.ts, packages/sync/src/links/OfflineLink.ts, packages/sync/src/links/RetryLink.ts, packages/sync/src/offline/OfflineQueue.ts, packages/sync/src/offline/OfflineQueueListener.ts, packages/sync/src/offline/OfflineRestoreHandler.ts, packages/sync/src/offline/OperationQueue.ts, packages/sync/src/offline/OperationQueueEntry.ts, packages/sync/src/offline/retry/RetriableOperation.ts, packages/sync/src/utils/helpers.ts, packages/sync/test/LocalDirectiveFilterLink.test.ts, packages/sync/test/SyncConfigTest.ts, packages/sync/test/createOptimisticResponseTest.ts, packages/sync/test/operations.ts
:lipstick: Cosmetic Improvements
=> Improvements

packages/sync/src/offline/OfflineQueue.ts
Add simple check for optimistic response operation.
=> fix: Add check for optimistic response

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json, packages/sync-cordova/package.json, packages/sync-cordova/plugin.xml, packages/sync/package.json
=> chore: release 2.3.1

packages/sync/integration_test/server/schema.js, packages/sync/integration_test/test/conflict.test.js, packages/sync/integration_test/test/offline.test.js, packages/sync/integration_test/utils/graphql.queries.js
https://issues.jboss.org/browse/AEROGEAR-8801
To run integration tests:
1. `npm install`
2. `npm run bootstrap`
3. `npm run build`
4. `cd packages/sync/integration_test`
5. `npm install`
6. `npm test`
=> Extend integration tests for data sync - conflicts

tsconfig.json
build failing on linux see the following gist for error https://gist.github.com/austincunningham/856e542ea421ec86c2ce3a54ac6fcf13  
adding dom to the tsconfig fixes the issue
=> fix: fix build that was failing on linux(AEROGEAR-8800)

packages/security/package.json, packages/security/src/appSecurity/AppSecurity.ts, packages/security/src/index.ts
Merging to feature branch `app-security`
PR Gets device data and app data for the security services app-service module
Uses MetricsBuilder
Needed for the Mobile security service Go server app-security integration
https://issues.jboss.org/browse/AEROGEAR-8773
- node 10
- npm 6
- install ionic https://ionicframework.com/docs/installation/cli
- install android sdk 26 http://www.androiddocs.com/sdk/installing/adding-packages.html
- clone this repo
- checkout branch AEROGEAR-8773
- install the aerogear-js-sdk
```bash
npm i && npm run bootstrap && npm run build
```
- clone https://github.com/austincunningham/ionic-showcase.git
- checkout branch AEROGEAR-8773
- change the package.json to point at your local clone of aerogear-js-sdk e.g.
> Note you can try and use npm link but I didn't have much …
=> AEROGEAR-8773 get device data

.circleci/config.yml, .coveralls.yml, README.md, package.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/push/package.json, packages/security/package.json, packages/sync/package.json
Moved test coverage from individual packages to root, so that there is single coverage report, that can be sent to coveralls.
=> feat: Added coveralls

packages/app/src/index.ts, packages/core/src/metrics/MetricsService.ts
Moving the call for publish from the MetricsService constructor to AeroGearApp
See discussion https://groups.google.com/forum/#!topic/aerogear/OiolsJTx4IY
=> fix(metricService): remove the publish from the MetricsService constructor and add this to AeroGearApp

.github/CODEOWNERS, docs/contrib/contributing-guide.adoc, scripts/cloneExamples.sh
Minor fix for documentation pointing to recent showcase application
=> fix: Update showcase application link

docs/templates/package.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/core/src/metrics/DefaultMetricsBuilder.ts, packages/core/src/metrics/MetricsService.ts, packages/core/src/metrics/index.ts, packages/core/src/metrics/model/MetricsBuilder.ts, packages/core/src/metrics/model/index.ts, packages/core/test/metrics/MetricsBuilderTest.ts, packages/core/test/metrics/MetricsServiceTest.ts, packages/push/package.json, packages/security/package.json, packages/security/src/appSecurity/AppSecurity.ts, packages/security/src/index.ts, packages/security/test/AppSecurityTest.ts, packages/security/test/config/mobile-services.json, packages/sync/package.json, packages/sync/src/links/LinksBuilder.ts
AppSecurity module for Application trust in the security module
=> App security

README.md
Changed link to Ionic Showcase Application
=> fix: changed link to showcase app

packages/sync/src/config/DataSyncConfig.ts, packages/sync/src/offline/OfflineLink.ts
this interface location was missed in a previous pr
=> fix: change path to moved interface

packages/auth/src/Auth.ts, packages/sync/src/auth/AuthContextProvider.ts, packages/sync/src/links/WebsocketLink.ts
=> fix: add clientId to auth payload delivered by subscriptions

packages/push/src/PushRegistration.ts, packages/push/test/PushRegistrationTest.ts
Add a method to unregistered a device on unified push server
You can use the ionic-showcase [AEROGEAR-9230](https://github.com/danielpassos/ionic-showcase/tree/AEROGEAR-9230) branch to test it
=> Add push unregister

RELEASE_NOTES.md
Idea for this file will be to stage release notes in the repository that will help me with releases. Our release notes are very thin now this file will allow us to drop more things into the release notes.
=> RELEASE_NOTES.md

RELEASE_NOTES.md, packages/sync/package.json, packages/sync/src/ApolloOfflineClient.ts, packages/sync/src/OfflineClient.ts
Update Apollo 2.6.0 and made modifications to support new typescript typings.
=> fix: Support for Apollo 2.6

packages/sync/src/index.ts
=> fix: re-export missing packages

packages/push/test/PushRegistrationTest.ts
Add some miss scenario for push tests
=> Improve push test coverage

.circleci/config.yml, scripts/versionMaster.sh
Publishing master fails now [1]. When lerna versions packages, it needs to commit the changes. For this git user needs to be configured.
[1] https://circleci.com/gh/aerogear/aerogear-js-sdk/2068?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> configure git user

packages/auth/src/Auth.ts, packages/sync/src/auth/AuthContextProvider.ts, packages/sync/src/links/AuthLink.ts, packages/sync/src/links/WebsocketLink.ts
For verification, if you link up these changes into the showcase app, you should be able to follow the same steps provided here: https://github.com/aerogear/ionic-showcase/pull/228
And ideally you shouldn't see any issues.
=> breaking: refactor AuthContextProvider interfaces, remove token

package.json, packages/sync/package.json, scripts/syncDevEnvironment.sh
added a small script to the base of the sdk to make developing and testing the sdk much easier.
NOTE: it assumes offix is in the same directory as the aerogear-sdk
=> chore: added script to make development easier

RELEASE_NOTES.md
@wtrocki @StephenCoady I've added an **Unreleased** section following a format/standard called [Keep a Changelog](https://keepachangelog.com/en/0.3.0/)
When we go to cut a release we simply rename the unreleased heading to the new version and start a new unreleased section. Let me know what you think.
=> chore: update release notes

packages/sync/src/ApolloOfflineClient.ts, packages/sync/src/OfflineClient.ts
=> breaking: rename offlineMutation -> offlineMutate

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json, packages/sync-cordova/package.json, packages/sync-cordova/plugin.xml, packages/sync/package.json
=> fix: release v2.6.0

RELEASE_NOTES.md
=> fix: add new item to release notes

packages/core/src/PlatformUtils.ts, packages/push/package.json, packages/push/src/AbstractPushRegistration.ts, packages/push/src/PushRegistration.ts, packages/push/src/PushRegistrationInterface.ts, packages/push/src/impl/PushRegistrationCordovaImpl.ts, packages/push/src/impl/PushRegistrationWebpushImpl.ts, packages/push/src/impl/index.ts, packages/push/test/PushRegistrationCordovaImplTest.ts, packages/push/test/PushRegistrationTest.ts, packages/push/test/PushRegistrationWebPushImplTest.ts
**JIRA**: https://issues.jboss.org/browse/AEROGEAR-9895
- Added support for the webpush
- Changed the library so that it can used without `cordova` (for webpush)
- Refactored the code adding some OO structure
=> Added web-push support

packages/push/src/impl/PushRegistrationWebpushImpl.ts, packages/push/test/PushRegistrationWebPushImplTest.ts
JIRA: [AEROGEAR-9899](https://issues.jboss.org/browse/AEROGEAR-9899)
=> Added detection of platform not supporting webpush

packages/sync/src/index.ts
=> fix(sync): export createClient method

packages/sync/src/DataSyncClient.ts, packages/sync/src/config/SyncConfig.ts
=> fix: ensure config is initialized properly

packages/sync/package.json
=> chore: bump offix-client to 0.9.0

lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json, packages/sync-cordova/package.json, packages/sync-cordova/plugin.xml, packages/sync/package.json
=> chore: release 2.8.0-rc1

RELEASE_NOTES.md, lerna.json, packages/app/package.json, packages/auth/package.json, packages/core/package.json, packages/metrics-cordova/package.json, packages/metrics-cordova/plugin.xml, packages/push-cordova/package.json, packages/push-cordova/plugin.xml, packages/push/package.json, packages/security-cordova/package.json, packages/security-cordova/plugin.xml, packages/security/package.json, packages/sync-cordova/package.json, packages/sync-cordova/plugin.xml, packages/sync/package.json
=> chore: release 2.8.0
